from sys import platform

# This is sent to IQFeed using "S,SET PROTOCOL,{PROTOCOL}" on each API launch.
PROTOCOL = "6.2"

# GCP Storage bucket names for each security type below. These buckets store the
# historical interval data for all of the SECURITIES listed in config.py.
BUCKETS = {
    "FOREX": "fractal_forex",
    "FUTURES": "fractal_futures",
}

# This is a dictionary of sec_type_id for querying symbols from the IQFeed API.
# Use the codes returned by the API to initiate Kafka topics.
#
# FXCM and COMP are separate FX exchanges where COMP is the Composite Symbol for
# the TENFORE exchange. For futures contracts, the '#' symbol represents the
# perpetual front month contract and '#C' is the adjusted continuous contract.
SECURITIES = {
    "FOREX": [
        "AUDCAD.FXCM",
        "AUDCHF.FXCM",
        "AUDJPY.FXCM",
        "AUDNZD.FXCM",
        "AUDSGD.FXCM",
        "AUDUSD.FXCM",
        "CADCHF.FXCM",
        "CADCNH.FXCM",
        "CADJPY.FXCM",
        "CHFJPY.FXCM",
        "EURAUD.FXCM",
        "EURCAD.FXCM",
        "EURCHF.FXCM",
        "EURCNH.FXCM",
        "EURGBP.FXCM",
        "EURNZD.FXCM",
        "EURSGD.FXCM",
        "EURUSD.FXCM",
        "EURZAR.FXCM",
        "GBPAUD.FXCM",
        "GBPCAD.FXCM",
        "GBPCHF.FXCM",
        "GBPCNH.FXCM",
        "GBPEUR.FXCM",
        "GBPJPY.FXCM",
        "GBPNZD.FXCM",
        "GBPSGD.FXCM",
        "GBPUSD.FXCM",
        "GBPZAR.FXCM",
        "NZDCAD.FXCM",
        "NZDCHF.FXCM",
        "NZDCNH.FXCM",
        "NZDJPY.FXCM",
        "NZDUSD.FXCM",
        "SGDJPY.FXCM",
        "USDCAD.FXCM",
        "USDCHF.FXCM",
        "USDCNH.FXCM",
        "USDHKD.FXCM",
        "USDJPY.FXCM",
        "USDMXN.FXCM",
        "USDSGD.FXCM",
        "USDTRY.FXCM",
        "USDZAR.FXCM",
        "AUDCAD.COMP",
        "AUDCHF.COMP",
        "AUDCNH.COMP",
        "AUDJPY.COMP",
        "AUDNZD.COMP",
        "AUDSGD.COMP",
        "AUDUSD.COMP",
        "CADCHF.COMP",
        "CADCNH.COMP",
        "CADJPY.COMP",
        "CHFJPY.COMP",
        "EURAUD.COMP",
        "EURCAD.COMP",
        "EURCHF.COMP",
        "EURCNH.COMP",
        "EURGBP.COMP",
        "EURNZD.COMP",
        "EURSGD.COMP",
        "EURUSD.COMP",
        "EURZAR.COMP",
        "GBPAUD.COMP",
        "GBPCAD.COMP",
        "GBPCHF.COMP",
        "GBPCNH.COMP",
        "GBPEUR.COMP",
        "GBPJPY.COMP",
        "GBPNZD.COMP",
        "GBPSGD.COMP",
        "GBPUSD.COMP",
        "GBPZAR.COMP",
        "NZDCAD.COMP",
        "NZDCHF.COMP",
        "NZDCNH.COMP",
        "NZDJPY.COMP",
        "NZDUSD.COMP",
        "SGDJPY.COMP",
        "USDCAD.COMP",
        "USDCHF.COMP",
        "USDCNH.COMP",
        "USDHKD.COMP",
        "USDJPY.COMP",
        "USDMXN.COMP",
        "USDSGD.COMP",
        "USDTRY.COMP",
        "USDZAR.COMP",
    ],
    # FUTURE: triple = (symbol, listed_market_id, description)
    "FUTURES": [
        ("@3N#C", "111", "3 YR US TREASURY NOTE"),
        ("@C#C", "111", "CORN"),
        ("@FF#C", "111", "30 DAY FED FUND"),
        ("@FV#C", "111", "5 YR US TREASURY NOTE"),
        ("@S#C", "111", "SOYBEANS"),
        ("@TU#C", "111", "2 YR US TREASURY NOTE"),
        ("@TY#C", "111", "10 YR US TREASURY NOTE"),
        ("@UB#C", "111", "ULTRA US TREASURY BOND"),
        ("@US#C", "111", "US TREASURY BOND"),
        ("@W#C", "111", "WHEAT"),
        ("@2YY#C", "111", "MICRO 2 YEAR YIELD"),
        ("@5YY#C", "111", "MICRO 5 YEAR YIELD"),
        ("@10Y#C", "111", "MICRO 10 YEAR YIELD"),
        ("@MYM#C", "111", "MICRO E-MINI DOW JONES"),
        ("@MKC#C", "42", "MINI KC HRW WHEAT"),
        ("@YC#C", "42", "MINI CORN"),
        ("@YK#C", "42", "MINI SOYBEAN"),
        ("@YW#C", "42", "MINI WHEAT"),
        ("@VX1#C", "32", "VIX WEEKLYS WEEK 1"),
        ("@VX2#C", "32", "VIX WEEKLYS WEEK 2"),
        ("@VX4#C", "32", "VIX WEEKLYS WEEK 4"),
        ("@VX#C", "32", "CBOE VOLATILITY INDEX"),
        ("@VXM#C", "32", "MINI CBOE VOLATILITY INDEX"),
        ("@AD#C", "110", "AUSTRALIAN DOLLAR"),
        ("@BP#C", "110", "BRITISH POUND"),
        ("@BTC#C", "110", "BITCOIN FUTURES"),
        ("@CD#C", "110", "CANADIAN DOLLAR"),
        ("@EU#C", "110", "EURO"),
        ("@GF#C", "110", "FEEDER CATTLE"),
        ("@HE#C", "110", "LEAN HOGS"),
        ("@JY#C", "110", "JAPANESE YEN"),
        ("@LBR#C", "110", "LUMBER"),
        ("@LE#C", "110", "LIVE CATTLE"),
        ("@M6A#C", "110", "E-MICRO AUD/USD"),
        ("@MCD#C", "110", "E-MICRO CAD/USD"),
        ("@MSF#C", "110", "E-MICRO CHF/USD"),
        ("@M6E#C", "110", "E-MICRO EUR/USD"),
        ("@M6B#C", "110", "E-MICRO GBP/USD"),
        ("@NE#C", "110", "NEW ZEALAND DOLLAR"),
        ("@RA#C", "110", "SOUTH AFRICAN RAND"),
        ("@SF#C", "110", "SWISS FRANC"),
        ("@ES#C", "43", "E-MINI S&P 500"),
        ("@NQ#C", "43", "E-MINI NASDAQ 100"),
    ],
}
